[package]
name = "lia-tests"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@stanford.edu>"]

[dependencies]
lia = { path = "../lia" }
lia-plugin = { path = "../lia-plugin" }
lia-runtime = { path = "../lia-runtime" }
