[package]
name = "lia-lang"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@stanford.edu>"]
build = "build.rs"

[lib]
name = "lia_lang"
crate-type = ["dylib"]

[dependencies]
lalrpop-util = "0.11.0"

[build-dependencies]
lalrpop = "0.11.0"
