[package]
name = "lia-jit"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@stanford.edu>"]

[dependencies]
llvm-alt = "0.4.0"
llvm-sys = "0.3.0"
lia = { path = "../lia", version = "0.1.0" }
lia-plugin = { path = "../lia-plugin", version = "0.1.0" }
